name = "Numssp"
uuid = "bcd14c31-b0d4-4eae-b592-0213e767a021"
authors = ["brianyjtai1994 <brianyjtai1994@gmail.com>"]
version = "0.1.3"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.5"
